import type { PMOSScreenSchema } from '../schema';

export const xiaoqiaoDebugAutomationSchema: PMOSScreenSchema = {
  schemaVersion: '1.0',
  screenId: 'xiaoqiao-debug-automation',
  screenType: 'debug-automation-workbench',
  workflowStage: 'integration',
  title: '小乔智投自动联调工作台',
  description: '在会话中承接从需求路由、资料确认、发起联调、过程观测到结果沉淀的完整链路。',
  productContext: {
    productId: 'xiaoqiao-ad-agent',
    productName: '小乔智投',
    projectId: 'debug-automation',
    projectName: '自动联调',
    requirementId: 'R-AUTO-01-R-AUTO-04',
    requirementTitle: '广告联调自动化任务创建、执行观测、异常接管与结果沉淀',
    stageOwner: '广告技术支持',
    targetRole: 'operator',
  },
  layout: {
    desktop: 'chat-first',
    mobile: 'stacked-decision-flow',
    density: 'high',
    stickyActions: true,
  },
  regions: {
    contextRail: [
      {
        type: 'ContextRail',
        id: 'debug-context',
        title: '联调背景',
        items: [
          { label: '媒体', value: '巨量 / 抖音', status: 'normal' },
          { label: '终端', value: 'Android', status: 'normal' },
          { label: '方式', value: '扫码联调', status: 'normal' },
          { label: '执行', value: '半自动，可人工接管', status: 'warning' },
        ],
      },
    ],
    main: [
      {
        type: 'ConversationPanel',
        id: 'debug-chat-flow',
        title: '联调会话',
        aiAssistanceMode: 'automation',
        summary: '用户在会话中提出联调目标，小乔识别意图后生成任务表单、待确认项和执行入口。',
        evidenceRefs: ['debug-flow-pdf', 'debug-design-doc'],
        sourceRefs: [
          'docs/sources/inbox/小乔智投-架构与联调流程-2026-05-13.pdf',
          'docs/sources/inbox/小乔智投/v1.1-0509/小乔智投-自动联调设计-2026-05-08.md',
        ],
      },
      {
        type: 'RequirementIntakeCard',
        id: 'debug-task-form',
        title: '联调资料确认',
        summary: '收集媒体、联调类型、账号、应用、包名、测试设备、环境和当前卡点，缺项时先追问或写入待办。',
        workflowStage: 'integration',
        sourceRefs: ['debug-flow-pdf', 'debug-design-doc'],
      },
      {
        type: 'WorkflowStatusPanel',
        id: 'debug-execution-status',
        title: '执行进展',
        workflowStage: 'integration',
        status: 'running',
        currentStep: 'Web 准备、移动端扫码、查找广告、拉起应用、成功轮询按状态机推进。',
      },
      {
        type: 'AIRecommendationCard',
        id: 'debug-next-step',
        title: '下一步建议',
        summary: '资料完整时建议发起自动联调；执行异常时建议查看最近截图和日志后选择重试或人工接管。',
        aiAssistanceMode: 'automation',
        evidenceRefs: ['debug-step-trace', 'debug-result-report'],
        recommendedActions: [
          {
            id: 'start-debug-task',
            label: '发起联调',
            actionType: 'advance_workflow',
            riskLevel: 'medium',
            approvalPolicy: 'human-review',
            auditRequired: true,
            targetObject: 'DebugAutomationTask',
          },
          {
            id: 'takeover-debug-task',
            label: '人工接管',
            actionType: 'request_review',
            riskLevel: 'high',
            approvalPolicy: 'human-review',
            requiresApproval: true,
            auditRequired: true,
            targetObject: 'DebugAutomationTask',
            rollbackPlan: '保留当前步骤、截图和日志，人工处理后继续或结束任务。',
          },
        ],
      },
    ],
    sidePanel: [
      {
        type: 'DynamicSurfaceCard',
        id: 'debug-live-observation',
        title: '联调观测面板',
        surfaceKind: 'side-sheet',
        sourceRefs: ['debug-flow-pdf'],
        evidenceRefs: ['debug-step-trace'],
      },
      {
        type: 'AgentControlCard',
        id: 'debug-agent-control',
        title: '联调控制',
        agentRole: '自动联调 Agent',
        summary: '控制发起、暂停、继续、重试和人工接管，所有高风险动作进入审计记录。',
        recommendedActions: [
          {
            id: 'pause-debug-task',
            label: '暂停执行',
            actionType: 'advance_workflow',
            riskLevel: 'medium',
            approvalPolicy: 'human-review',
            auditRequired: true,
          },
        ],
      },
    ],
    evidencePanel: [
      {
        type: 'EvidencePanel',
        id: 'debug-evidence',
        title: '截图、日志与结果依据',
        evidenceRefs: ['debug-step-trace', 'debug-result-report'],
        sourceRefs: [
          'docs/sources/inbox/小乔智投-架构与联调流程-2026-05-13.pdf',
          'docs/sources/inbox/小乔智投/v1.1-0509/小乔智投-自动联调实施方案-2026-05-08.md',
        ],
        lastUpdatedAt: '2026-05-13T18:01:00+08:00',
      },
      {
        type: 'SourceReferenceList',
        id: 'debug-sources',
        title: '来源',
        sourceRefs: [
          'docs/sources/inbox/小乔智投-架构与联调流程-2026-05-13.pdf',
          'docs/sources/inbox/小乔智投/v1.1-0509/小乔智投-自动联调设计-2026-05-08.md',
          'docs/sources/inbox/小乔智投/v1.1-0509/小乔智投-自动联调实施方案-2026-05-08.md',
        ],
        lastUpdatedAt: '2026-05-13T18:01:00+08:00',
      },
    ],
    approvalPanel: [
      {
        type: 'ApprovalPanel',
        id: 'debug-approval',
        title: '高风险动作确认',
        approvalPolicy: 'human-review',
        actions: [
          {
            id: 'approve-debug-start',
            label: '确认发起联调',
            actionType: 'approve_change',
            riskLevel: 'high',
            approvalPolicy: 'human-review',
            requiresApproval: true,
            auditRequired: true,
            targetObject: 'DebugAutomationTask',
            rollbackPlan: '可暂停任务并保留已产生的截图与日志。',
          },
        ],
      },
    ],
    auditTrail: [
      {
        type: 'AuditLog',
        id: 'debug-audit',
        title: '联调记录',
        logs: [
          {
            id: 'debug-audit-1',
            actor: '小乔',
            action: '识别联调需求并生成任务表单',
            timestamp: '2026-05-13T18:01:00+08:00',
            result: 'completed',
          },
        ],
      },
    ],
  },
  evidenceRefs: ['debug-flow-pdf', 'debug-step-trace', 'debug-result-report'],
  sourceRefs: [
    'docs/sources/inbox/小乔智投-架构与联调流程-2026-05-13.pdf',
    'docs/sources/inbox/小乔智投/v1.1-0509/小乔智投-自动联调设计-2026-05-08.md',
  ],
  lastUpdatedAt: '2026-05-13T18:01:00+08:00',
  decisionPolicy: 'approve',
  approvalPolicy: 'human-review',
  riskLevel: 'medium',
  auditRequired: true,
  aiAssistanceMode: 'automation',
  recommendedActions: [
    {
      id: 'implement-debug-workbench',
      label: '实现自动联调全过程前端',
      actionType: 'advance_workflow',
      riskLevel: 'medium',
      approvalPolicy: 'human-review',
      auditRequired: true,
      targetObject: 'imported/projects/src/app/page.tsx',
    },
  ],
};
