apps:
  三国杀OL: "10100002"
  X2game-日本: "10700027"
  里世界-海外全球: "10200071"
  指间山海: "10300001"
  指间: "10300001"
  海外:
    - "10700027"
    - "10200071"
    - "10200466"
    - "10200445"
media:
  巨量广告: "10001"
  巨量: "10001"
  头条: "10001"
  今日头条: "10001"
  巨量引擎: "10001"
  抖音广告: "10001"
  抖音: "10001"
  字节跳动: "10001"
  腾讯广告: "10002"
  腾讯: "10002"
  微信广告: "10002"
  微信: "10002"
  广点通: "10002"
  Facebook: "20001"
  脸书: "20001"
  FB: "20001"
  Tiktok: "20002"
  TikTok Ads: "20002"
  TikTok广告: "20002"
  Google: "20003"
  谷歌: "20003"
teams:
  上海发行项目部: "1"
  上海投放: "1"
  上海: "1"
  广告投放一部（杭州）: "2"
  杭州投放: "2"
  杭州: "2"
  杭州投放一部: "2"
  广州发行二部: "209"
  广州投放二部: "209"
  广州二部: "209"
  广州发行一部: "221"
  广州投放: "221"
  广州投放一部: "221"
  广州一部: "221"
  创新部: "244"
  飞涛: "247"
  市场部: "248"
dimensions:
  apps:
    - appId: "10100002"
      appName: "三国杀OL"
      appRegion: "MAINLAND"
      thirdPartAppTypes: "手游,页游,H5游戏"
      spMultiTeam: 1
    - appId: "10700027"
      appName: "X2game-日本"
      appRegion: "OVERSEAS"
      thirdPartAppTypes: "手游"
      spMultiTeam: 0
    - appId: "10200071"
      appName: "里世界-海外全球"
      appRegion: "OVERSEAS"
      thirdPartAppTypes: "手游"
      spMultiTeam: 1
    - appId: "10300001"
      appName: "指间山海"
      appRegion: "MAINLAND"
      thirdPartAppTypes: "手游"
      spMultiTeam: 1
    - appId: "10200466"
      appName: "脱敏4"
      appRegion: "OVERSEAS"
      thirdPartAppTypes: "手游"
      spMultiTeam: 0
    - appId: "10200445"
      appName: "脱敏5"
      appRegion: "OVERSEAS"
      thirdPartAppTypes: "手游"
      spMultiTeam: 0
  media:
    - media_id: "10001"
      media_name: "巨量广告"
      promotion_source: "AD"
      region: "MAINLAND"
      media_ad_type: "COMMON"
      query_start_date: "2025-01-01"
    - media_id: "10002"
      media_name: "腾讯广告"
      promotion_source: "AD"
      region: "MAINLAND"
      media_ad_type: "COMMON"
      query_start_date: "2025-01-01"
    - media_id: "10003"
      media_name: "快手广告"
      promotion_source: "AD"
      region: "MAINLAND"
      media_ad_type: "COMMON"
      query_start_date: "2025-01-01"
    - media_id: "10016"
      media_name: "苹果广告"
      promotion_source: "AD"
      region: "MAINLAND"
      media_ad_type: "SEARCH"
      query_start_date: "2025-01-01"
    - media_id: "10141"
      media_name: "广告星图"
      promotion_source: "AD"
      region: "MAINLAND"
      media_ad_type: "COMMON"
      query_start_date: "2025-01-01"
    - media_id: "20001"
      media_name: "Facebook"
      promotion_source: "AD"
      region: "OVERSEAS"
      media_ad_type: "COMMON"
      query_start_date: "2025-01-01"
    - media_id: "20002"
      media_name: "Tiktok"
      promotion_source: "AD"
      region: "OVERSEAS"
      media_ad_type: "COMMON"
      query_start_date: "2025-01-01"
    - media_id: "20003"
      media_name: "Google"
      promotion_source: "AD"
      region: "OVERSEAS"
      media_ad_type: "COMMON"
      query_start_date: "2025-01-01"
  teams:
    - team_ids: "1"
      team_name: "上海发行项目部"
      query_start_date: "2025-01-01"
    - team_ids: "2"
      team_name: "广告投放一部（杭州）"
      query_start_date: "2025-01-01"
    - team_ids: "209"
      team_name: "广州发行二部"
      query_start_date: "2025-01-01"
    - team_ids: "221"
      team_name: "广州发行一部"
      query_start_date: "2025-01-01"
    - team_ids: "244"
      team_name: "创新部"
      query_start_date: "2025-01-01"
    - team_ids: "247"
      team_name: "飞涛"
      query_start_date: "2025-01-01"
    - team_ids: "248"
      team_name: "市场部"
      query_start_date: "2025-01-01"
