import type { PromptConfig } from '@/types';

export type ManagedPromptSeed = {
  config: Partial<PromptConfig> & { id: string };
  content: string;
  author?: string;
  change_note?: string;
  seed_revision: string;
};

const CHAT_VISIBILITY = {
  main_chat: ['answer_markdown', 'visualizations'],
  card: ['visualizations'],
  right_panel: ['evidence_bundle', 'execution_context', 'prompt_config'],
  internal_only: ['raw_prompt', 'secrets', 'tokens'],
};

export const MANAGED_RUNTIME_PROMPT_SEED_REVISION = '2026-06-07.model-use-case-v1';

const MODEL_USE_CASE_FORBIDDEN_ACTIONS = [
  '禁止生成 MCP final arguments、toolArguments 或 finalArgs。',
  '禁止生成 mediaId、appId、projectId 等最终 ID。',
  '禁止生成 promotionSource external value；只能输出内部语义候选。',
  '禁止判断权限、绕过 preflight、绕过 schema enum 校验。',
  '禁止把工具错误解释为无数据、成功或业务结论。',
  '禁止编造未返回的数据，禁止修改工具返回数字、金额、ROI、日期和维度。',
].join('\n');

function modelUseCasePrompt(params: {
  id: string;
  name: string;
  node: string;
  outputContract: string;
  taskInstruction: string;
  variables: string[];
  fewShot?: string;
}): ManagedPromptSeed {
  return {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: params.id,
      key: params.id,
      name: params.name,
      scope: params.node,
      expectation: params.taskInstruction,
      status: 'active',
      current_version: 1,
      binding: { workflow: 'chat_model_use_case', modelUseCase: params.node },
      category: 'model-use-case',
      applicable_workflows: ['chat'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      input_variables: params.variables,
      output_schema: { contract: params.outputContract },
      approval_status: 'not_required',
      enabled: true,
    },
    content: [
      '系统约束：你是受治理的 LLM 调用点，只能根据输入生成结构化理解、任务规划候选、风险说明或基于证据的表达。',
      '域策略：工具执行、Resolver 决策、权限、schema adapter、preflight、业务错误归一化和 ResponseContract 过滤都由确定性代码负责。',
      `任务说明：${params.taskInstruction}`,
      `输出契约：只输出一个符合 ${params.outputContract} 的 JSON 对象，不输出 Markdown、解释性前后缀、隐藏推理或额外字段。`,
      `禁止行为：\n${MODEL_USE_CASE_FORBIDDEN_ACTIONS}`,
      '兜底策略：如果输入要求你给最终工具参数或最终 ID，只返回空候选和 notes，不输出参数对象。',
      ...(params.fewShot ? [`示例：\n${params.fewShot}`] : []),
    ].join('\n\n'),
    author: 'system',
    change_note: `初始化 ${params.node} 的受治理提示词`,
  };
}

const MODEL_USE_CASE_PROMPT_SEEDS: ManagedPromptSeed[] = [
  modelUseCasePrompt({ id: 'model-use-case.request_understanding', name: '请求理解提示词', node: 'request_understanding', outputContract: 'QueryUnderstandingContract', taskInstruction: '识别用户目标、指标、日期、维度、终端和歧义，只输出候选语义。', variables: ['message', 'history', 'projectContext'], fewShot: '输入：{"message":"昨天巨量消耗多少","history":[]}\n输出：{"intent":"report_query","metrics":["cost"],"date_range":{"start":"2026-06-15","end":"2026-06-15"},"dimensions":[],"ambiguity":[{"field":"media","reason":"未指定媒体，可能需要确认是否指巨量引擎"}]}' }),
  modelUseCasePrompt({ id: 'model-use-case.intent_routing_review', name: '意图路由候选提示词', node: 'intent_routing_review', outputContract: 'IntentRoutingContract', taskInstruction: '基于用户消息、对话历史、项目上下文、可用意图类型、业务规则和工具能力定义，生成意图路由候选。输出 intent_type、confidence（0-1）和 reason，供 Planner/Arbitrator 使用；不要声明最终执行路径。', variables: ['message', 'history', 'projectContext', 'availableIntentTypes', 'routeRules', 'capabilitySummary'] }),
  modelUseCasePrompt({ id: 'model-use-case.query_contract_building', name: '问数语义构建提示词', node: 'query_contract_building', outputContract: 'QueryUnderstandingContract', taskInstruction: '构建问数语义候选，包括 terminal_os 候选和 promotionSource 内部语义，不输出可执行参数。', variables: ['message', 'semanticCatalog', 'policy'] }),
  modelUseCasePrompt({ id: 'model-use-case.entity_candidate_extraction', name: '实体候选抽取提示词', node: 'entity_candidate_extraction', outputContract: 'DetectedEntityContract', taskInstruction: '抽取媒体、应用、项目、终端、渠道、指标和日期候选，不输出最终 ID。', variables: ['message', 'entityCatalog', 'resolverAliases'] }),
  modelUseCasePrompt({ id: 'model-use-case.ambiguity_detection', name: '歧义检测提示词', node: 'ambiguity_detection', outputContract: 'AmbiguityDecisionContract', taskInstruction: '识别未解决歧义或缺失信息，必要时给出一个用户追问建议。追问必须面向业务用户、简短、不涉及内部字段。如果缺失关键信息（如时间范围、指标名称），优先追问最关键的一项。如果没有歧义且信息充足，输出无歧义判定。', variables: ['message', 'resolvedFilters', 'missingFields'] }),
  modelUseCasePrompt({ id: 'model-use-case.resolver_disambiguation_review', name: 'Resolver 风险检查提示词', node: 'resolver_disambiguation_review', outputContract: 'AmbiguityDecisionContract', taskInstruction: '检查 Resolver 候选是否存在歧义，只给风险说明，不选择最终 ID。如果候选之间存在同名、别名或跨媒体冲突，说明风险等级和建议处理方式。', variables: ['message', 'resolverCandidates', 'selectionPolicy'] }),
  modelUseCasePrompt({ id: 'model-use-case.capability_ranking_review', name: '能力排序风险检查提示词', node: 'capability_ranking_review', outputContract: 'AmbiguityDecisionContract', taskInstruction: '说明能力排序风险，不覆盖能力清单、工具选择或执行策略。如果 top-1 和 top-2 能力得分接近，说明风险；如果某个能力明显更匹配，确认排序合理。', variables: ['message', 'capabilityCandidates', 'selectedCapability'] }),
  modelUseCasePrompt({ id: 'model-use-case.capability_discovery', name: '能力发现提示词', node: 'capability_discovery', outputContract: 'CapabilityUnderstandingContract', taskInstruction: '遍历每个工具的名称、描述和参数定义，理解其语义能力，输出与用户意图匹配的候选工具列表（含匹配度和原因）。IntentOrch 只能作为 planner candidate 与 arbitration summary 参考，不做最终工具选择，不输出最终参数。', variables: ['message', 'userRequirement', 'tools', 'entityCandidates', 'semanticCandidates', 'intentorch_candidate', 'planner_candidates', 'arbitration_summary'] }),
  modelUseCasePrompt({ id: 'model-use-case.tool_selection_review', name: '工具消歧选择提示词', node: 'tool_selection_review', outputContract: 'ToolSelectionDecisionContract', taskInstruction: '多工具竞争时（得分接近），结合用户消息、上下文和各候选工具的能力描述，选择最合适的工具并给出理由。只在 top-2 差距不明显时被调用。', variables: ['message', 'topCandidates', 'userRequirement', 'capabilityUnderstandings'] }),
  modelUseCasePrompt({ id: 'model-use-case.operation_risk_review', name: 'MCP失败解释提示词', node: 'operation_risk_review', outputContract: 'FailureExplanationContract', taskInstruction: '分析 MCP 工具调用失败原因、风险和用户可读说明。只输出观察、原因和建议用户如何补充信息；不得改变工具参数、工具选择或重试策略。', variables: ['message', 'toolName', 'errorInfo', 'callParams', 'retryCount'] }),
  modelUseCasePrompt({ id: 'model-use-case.trace_summary', name: '多轮状态继承提示词', node: 'trace_summary', outputContract: 'MultiTurnInheritanceContract', taskInstruction: '基于当前消息和历史对话，识别本轮用户想修改什么条件以及应从上轮继承什么条件（指标、维度、时间范围、实体、工具），输出结构化的 inheritedSlots 和 modification 说明。', variables: ['message', 'history', 'currentRequirement', 'previousSlotState'] }),
  modelUseCasePrompt({ id: 'model-use-case.required_input_assist', name: '缺参追问提示词', node: 'required_input_assist', outputContract: 'GroundedAnswerContract', taskInstruction: '把确定性缺参结果改写成清晰追问，只基于输入中的缺失项。追问必须面向业务用户，使用用户能理解的语言，不涉及内部字段名、工具参数或系统 ID。一次只追问最关键的一个缺失项。', variables: ['blockingRequirements', 'missingFields', 'toolContract'] }),
  modelUseCasePrompt({ id: 'model-use-case.data_result_interpretation', name: '数据结果解读提示词', node: 'data_result_interpretation', outputContract: 'GroundedInterpretationContract', taskInstruction: '只基于 semanticResult、sourceRefs 和 evidenceRefs 解读结果，不改变事实和数字。时间、节假日、季节、周末、暑假、系统升级等动态因素只有在证据中有明确关联时才能作为原因；弱相关只能写成待验证假设并说明验证数据，不能用常识猜原因。', variables: ['semanticResult', 'sourceRefs', 'evidenceRefs'], fewShot: '输入：{"semanticResult":{"rows":[{"date":"2026-06-15","cost":12345.67,"install":234}],"summary":"单日数据"},"sourceRefs":[{"title":"巨量引擎日报","source":"report_mcp"}]}\n输出：{"summary":"6月15日巨量引擎消耗12,345.67元，新增安装234个。","anomalies":[],"trends":[],"risk_flags":["single_day_no_trend"],"next_steps":["查看近7天趋势对比","按媒体拆分消耗占比"]}' }),
  modelUseCasePrompt({ id: 'model-use-case.report_summary', name: '问数结果总结提示词', node: 'report_summary', outputContract: 'GroundedInterpretationContract', taskInstruction: '基于工具返回和证据总结结果、风险和下一步检查点，不新增未返回事实。时间、节假日、季节、周末、暑假、系统升级等动态因素只有在工具数据、知识库、公开来源、历史同期或业务日历提供明确证据时才能作为原因；否则只能列为待验证假设或不提。', variables: ['semanticResult', 'toolChain', 'qualityCheck'], fewShot: '输入：{"semanticResult":{"metrics":["cost"],"dimensions":["date"],"rows_count":7},"toolChain":[{"status":"success","tool":"report_query"}]}\n输出：{"summary":"过去7天消耗数据已取回，整体呈上升趋势。","anomalies":[{"date":"2026-06-13","metric":"cost","change":"+23%","severity":"medium"}],"next_steps":["检查6月13日异常原因","对比上一周期"]}' }),
  modelUseCasePrompt({ id: 'model-use-case.diagnosis_summary', name: '诊断总结提示词', node: 'diagnosis_summary', outputContract: 'EvidenceGroundedDiagnosisContract', taskInstruction: '基于诊断结果和证据总结可能原因、风险和下一步动作，不编造原因。', variables: ['diagnosisResult', 'sourceRefs', 'evidenceRefs'], fewShot: '输入：{"diagnosisResult":{"issue_type":"callback_delay","affected_scope":"近24小时","confidence":"medium"},"sourceRefs":[{"title":"回传日志","source":"mcp"}]}\n输出：{"summary":"近24小时回传延迟率升至12%，主要影响Android端。","confidence":"medium","root_causes":[{"cause":"媒体SDK版本更新后回传通道异常","confidence":"medium","evidence":"日志显示v3.2.1 SDK回传失败率高于v3.1.0"}],"next_steps":["检查SDK版本分布","联系媒体技术支持确认是否有已知问题"]}' }),
  modelUseCasePrompt({ id: 'model-use-case.answer_composition', name: '答案组装提示词', node: 'answer_composition', outputContract: 'GroundedAnswerContract', taskInstruction: '把已验证的语义结果、证据和动作组织成用户可读答案，不修改 ResponseContract 字段。', variables: ['semanticResult', 'sourceRefs', 'evidenceRefs', 'actions'], fewShot: '输入：{"semanticResult":{"summary":"消耗环比上升15%"},"sourceRefs":[{"title":"日报","source":"report_mcp"}],"actions":[{"label":"查看趋势","type":"report_query"}]}\n输出：{"answerMarkdown":"近7天消耗环比上升15%，建议关注是否有新增投放计划。\\n\\n**来源**：日报","actions":[{"label":"查看趋势","type":"report_query"}]}' }),
  modelUseCasePrompt({ id: 'model-use-case.chat_answer', name: '通用回答提示词', node: 'chat_answer', outputContract: 'GroundedAnswerContract', taskInstruction: '只基于输入上下文、Planner 输出和 evidence_ledger 组织可读回答，不新增未返回事实。evidence_ledger 中存在 knowledge.hits、public_web.sources 或 answer_candidate 时，必须优先使用这些证据组织答案；证据不足时说明无法确认或给出待验证下一步，不得用模型常识替代证据。开放式能力说明和自我介绍必须综合 assistant_profile、capability_overview、Planner 候选、证据边界和用户约束，不得把用户角色或当前项目误说成助手身份。如果输入中存在 domain_context（业务流领域约束），必须遵守其中的回答格式和内容要求。', variables: ['message', 'baseAnswer', 'context', 'planner_output', 'evidence_ledger', 'answer_constraints', 'assistant_profile', 'capability_overview', 'planner_candidates', 'arbitration_summary', 'domain_context'] }),
  modelUseCasePrompt({ id: 'model-use-case.knowledge_answer', name: '知识回答提示词', node: 'knowledge_answer', outputContract: 'GroundedAnswerContract', taskInstruction: '只基于检索到的知识片段回答，缺失信息要明确说明。如果知识库命中了相关内容，用知识片段作为依据组织回答并标注来源。如果知识库未命中或内容不足，明确说明"知识库暂无相关信息"并给出替代建议。', variables: ['message', 'knowledgeHits', 'baseAnswer'] }),
  modelUseCasePrompt({ id: 'model-use-case.requirement_drafting', name: '需求草拟提示词', node: 'requirement_drafting', outputContract: 'DraftTextContract', taskInstruction: '把用户描述整理成简洁需求草稿，用于人工确认。', variables: ['message', 'history', 'baseDraft'] }),
  modelUseCasePrompt({
    id: 'model-use-case.recommendation',
    name: '动态推荐提示词',
    node: 'recommendation',
    outputContract: 'RecommendationContract',
    taskInstruction: '基于用户角色、最近会话、当前会话标题、当前场景和项目上下文，输出 3 条可直接发送的“下一步提问建议”，用于继续追问或扩展探索。',
    variables: ['roleLabel', 'recentConversations', 'recentTasks', 'activeFeatures', 'currentConversationTitle', 'activeAgent', 'projectContext'],
  }),
  modelUseCasePrompt({ id: 'conversation-title-generate', name: '会话标题生成提示词', node: 'conversation_title', outputContract: 'TitleTextContract', taskInstruction: '基于最新消息生成简短标题，只输出 titleText。', variables: ['message', 'history'] }),
  modelUseCasePrompt({ id: 'conversation-title-update', name: '会话标题更新提示词', node: 'conversation_title', outputContract: 'TitleTextContract', taskInstruction: '判断当前标题是否需要更新，只输出 titleText。', variables: ['currentTitle', 'latestMessages'] }),
  modelUseCasePrompt({ id: 'data-analysis-interpret', name: '数据分析解读提示词', node: 'data_analysis', outputContract: 'DataAnalysisContract', taskInstruction: '对数据进行多维度分析解读，包括同比、环比、趋势、占比、异常等，输出结构化分析结果。', variables: ['data', 'context', 'userQuestion'] }),
];

export const MANAGED_RUNTIME_PROMPT_SEEDS: ManagedPromptSeed[] = [
  ...MODEL_USE_CASE_PROMPT_SEEDS,
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'route_prompt',
      key: 'route_prompt',
      name: '路由层提示词',
      scope: 'route_prompt',
      expectation: '识别用户意图、业务范围和是否需要调用数据能力。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'chat_route' },
      category: 'chat-runtime',
      applicable_workflows: ['chat'],
      applicable_agents: ['hub'],
      visibility: CHAT_VISIBILITY,
      enabled: true,
    },
    content: [
      '你负责会话入口的意图路由，只输出可被系统消费的路由判断，不生成最终回答。',
      '输入包括用户问题、会话历史、隐藏项目上下文、已识别业务槽位和可用工具状态。',
      '识别业务对象、时间范围、媒体、终端、指标、维度，以及是否需要查数、诊断、需求沟通、帮助或联调。',
      '项目 ID / APPID 只能作为隐藏上下文和工具参数，不要写入用户可见正文，也不要诱导模型复述。',
      '仅当用户明确要数、表、趋势、对比、排名或报表交付时才进入 report_query；帮助咨询、字段解释、问题排查和系统操作不要被误送进报表链路。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文路由提示词',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'response_prompt',
      key: 'response_prompt',
      name: '回答生成提示词',
      scope: 'response_prompt',
      expectation: '控制主回答正文的结论、依据和建议表达。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'chat_response' },
      category: 'chat-runtime',
      applicable_workflows: ['chat'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      enabled: true,
    },
    content: [
      '你负责生成用户可见的主回答。',
      '回答顺序：先给业务结论，再给必要依据，最后给下一步建议。',
      '主对话禁止展示条件解析过程、参数说明、工具 arguments、HTTP 状态、原始 payload、项目 ID、APPID。',
      '如果已有结构化数据，正文只解释结论和使用方式，明细交给表格或图表。',
      '如果知识库、工具或权限失败，正文温和降级，不暴露请求地址和内部错误栈。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文回答提示词',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'evidence_prompt',
      key: 'evidence_prompt',
      name: '证据展示提示词',
      scope: 'evidence_prompt',
      expectation: '控制来源、证据和执行详情的可见层级。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'chat_evidence' },
      category: 'chat-runtime',
      applicable_workflows: ['chat'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      output_schema: { type: 'json', strict: false },
      enabled: true,
    },
    content: [
      '你负责组织来源、证据和执行详情的可见层级。',
      'source_refs、tool_chain、知识库状态、HTTP 状态、请求地址、工具参数、失败原因进入 evidence_bundle 或 execution_context。',
      '主对话只保留“可查看来源/执行详情”的轻入口，不默认展开证据。',
      '知识库失败时用户正文只说知识库暂不可用或已继续用可用信息回答，详细原因进入执行详情。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文证据提示词',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'card_prompt',
      key: 'card_prompt',
      name: '卡片展示提示词',
      scope: 'card_prompt',
      expectation: '控制结构化卡片展示哪些业务字段。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'chat_card' },
      category: 'chat-runtime',
      applicable_workflows: ['chat'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      output_schema: { type: 'json', strict: false },
      enabled: true,
    },
    content: [
      '你负责约束结构化卡片的语义内容，不直接决定前端组件样式。',
      '卡片只展示业务摘要、风险等级、置信度、业务影响和可执行建议。',
      '不要展示 structured_payload、execution_context、reasoning_artifacts、tool_chain 等内部字段名。',
      '问数结果卡片不得展示项目 ID、查询参数、来源时间、服务名、工具名和“已取回 N 行数据”作为主结果说明。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文卡片提示词',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'followup_prompt',
      key: 'followup_prompt',
      name: '追问建议提示词',
      scope: 'followup_prompt',
      expectation: '生成下一步追问和可执行动作。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'chat_followup' },
      category: 'chat-runtime',
      applicable_workflows: ['chat'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      output_schema: { type: 'json', strict: false },
      enabled: true,
    },
    content: [
      '你负责生成可继续处理的下一步动作。',
      '每个动作必须结构化表达 label、type、intent、action、risk_level、auto_executable。',
      'label 面向业务用户，简短可点击；action 面向系统执行，稳定可路由。',
      '高风险动作必须 auto_executable=false；低风险查询、导出、打开详情可以自动执行。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文追问提示词',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'tool_explain_prompt',
      key: 'tool_explain_prompt',
      name: '工具解释提示词',
      scope: 'tool_explain_prompt',
      expectation: '说明工具调用结果、失败降级和诊断信息的展示策略。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'chat_tool_explain' },
      category: 'chat-runtime',
      applicable_workflows: ['chat'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      enabled: true,
    },
    content: [
      '你负责把工具调用结果解释给运行时和执行详情，不直接污染主回答。',
      '工具失败时正文温和降级，详细失败原因、请求地址、HTTP 状态、知识库 ID 数量、参数和返回来源写入执行详情。',
      '工具成功时只把业务结论交给主回答，把原始返回、arguments、resolved_filters、preflight 和 selection_trace 放入详情。',
      '不要让用户在主对话看到内部服务名、接口字段名或原始 JSON。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文工具解释提示词',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'report_query_route_prompt',
      key: 'report_query_route_prompt',
      name: '问数路由提示词',
      scope: 'report_query_route_prompt',
      expectation: '识别自然语言问数意图、指标、维度、时间范围和是否需要补充条件。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'report_query' },
      category: 'report-query-runtime',
      applicable_workflows: ['report_query'],
      applicable_agents: ['report'],
      visibility: CHAT_VISIBILITY,
      enabled: true,
    },
    content: [
      '你负责识别广告投放问数请求。',
      '仅在已经确认用户要数、要表、要趋势、要对比或要报表交付时，才开始判断可用能力与候选报表。',
      '多个指标同时出现时，不要把它们直接写死成某一种报表；应结合时间范围、维度是否细分、指标组合和工具域能力综合判断。',
      '项目 ID / APPID 只能作为隐藏上下文或执行参数，不要写入用户正文。',
      '缺少必要条件时只追问业务条件，不展示内部参数解析过程，也不要把能力发现结果反向改写未确认的主意图。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文问数路由提示词',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'report_query_answer_prompt',
      key: 'report_query_answer_prompt',
      name: '问数回答提示词',
      scope: 'report_query_answer_prompt',
      expectation: '控制问数正文回答，避免暴露条件解析、来源时间和项目 ID。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'report_query.answer' },
      category: 'report-query-runtime',
      applicable_workflows: ['report_query'],
      applicable_agents: ['report'],
      visibility: CHAT_VISIBILITY,
      enabled: true,
    },
    content: [
      '问数回答先给业务结论，再说明可继续做什么。',
      '先解释为什么选择当前报表能力，再说明当前结果是大盘还是细分，以及数据是否足以判断。',
      '主对话不要单独展示“已取回 N 行数据”、来源时间、工具名、服务名、项目 ID、APPID、原始查询条件、参数说明或执行 payload。',
      '如果有数据，正文只说明数据已整理到下方表格或图表。',
      '如果查询失败或知识库降级，用温和文案说明“已继续用可用信息回答”，详细失败原因进入执行详情。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文问数回答提示词',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'report_query_visual_prompt',
      key: 'report_query_visual_prompt',
      name: '问数可视化提示词',
      scope: 'report_query_visual_prompt',
      expectation: '控制问数结果的数据表格、图表、数值格式和可见性边界。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'report_query.visual' },
      category: 'report-query-runtime',
      applicable_workflows: ['report_query'],
      applicable_agents: ['report'],
      visibility: CHAT_VISIBILITY,
      output_schema: { type: 'json', strict: false },
      enabled: true,
    },
    content: [
      '你负责生成问数结果的数据视图，不负责复述查询过程。',
      '视图选择规则：趋势、每日、按日、近 N 天、折线或图表类问题优先生成图表；明细、列表、核对、导出类问题优先生成表格。',
      '表格规则：有 rows/columns 时必须生成可读明细视图；字段名面向业务用户；隐藏 projectId、appId、token、key、内部 id 和全空字段；空值显示为 --。',
      '表格规则：数值展示必须由 UI 统一格式化，金额、成本、消耗、收入、ROI、比例、人数、次数等指标统一保留小数点后两位；百分比保留两位并带 %。',
      '表格规则：主对话只展示轻量预览和“查看完整表格”入口；完整明细进入弹窗表格，支持横向滚动、稳定列宽、排序筛选和导出。',
      '图表规则：只有存在 semantic_result 且数据结构满足时展示图表；趋势类优先折线/柱状，明细和多字段核对类优先表格。',
      '可信规则：趋势图至少需要 2 个有效日期点；不足时不要输出趋势结论，展示数据不足说明和下一步动作。',
      '图表规则：图表失败不得影响表格展示，主对话可温和提示“图表暂不可用，表格数据如下”，渲染失败原因进入执行详情。',
      '可见性规则：主对话禁止展示已取回 N 行、来源时间、工具名、接口名、查询条件、项目 ID、APPID、参数说明、raw JSON 和 datatype。',
      '降级规则：没有可展示数据时给业务化空结果说明和下一步建议，不把空表格或执行 payload 展示给用户。',
    ].join('\n'),
    author: 'system',
    change_note: '补齐问数趋势图优先级和数据不足可信规则',
  },
  {
    seed_revision: MANAGED_RUNTIME_PROMPT_SEED_REVISION,
    config: {
      id: 'report_query_evidence_prompt',
      key: 'report_query_evidence_prompt',
      name: '问数证据提示词',
      scope: 'report_query_evidence_prompt',
      expectation: '控制问数来源、工具调用和失败原因进入执行详情，不污染主回答。',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'report_query.evidence' },
      category: 'report-query-runtime',
      applicable_workflows: ['report_query'],
      applicable_agents: ['report'],
      visibility: CHAT_VISIBILITY,
      output_schema: { type: 'json', strict: false },
      enabled: true,
    },
    content: [
      '来源 Tab 展示业务可读来源，执行详情 Tab 展示 tool name、arguments、raw rows、datatype、endpoint、httpStatus、trace、diagnostics、prompt_config。',
      '主回答只给业务结论和下一步动作，不展示工具参数、原始 rows、接口地址或内部字段名。',
      '当工具失败、权限不足或能力缺失时，把失败原因、缺失字段、候选工具和诊断信息写入执行详情。',
    ].join('\n'),
    author: 'system',
    change_note: '修复为 UTF-8 中文问数证据提示词',
  },
  // ──── P1-#1: 业务流领域约束提示词（注入 chat_answer 的 domain_context） ────
  {
    seed_revision: '2026-06-16.domain-context-v1',
    config: {
      id: 'help.answer',
      key: 'help.answer',
      name: '帮助回答领域约束',
      scope: 'help.answer',
      expectation: '控制使用帮助类回答的结构：定义、适用场景、入口路径、注意事项和下一步建议',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'help', agent: 'answer' },
      category: 'business-flow',
      applicable_workflows: ['help'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你正在回答一个使用帮助类问题。请按以下结构组织回答：',
      '',
      '1. **定义说明**：用一句话解释指标/功能/规则是什么。',
      '2. **适用场景**：什么情况下会用到，典型使用场景举例。',
      '3. **入口路径**：在系统中去哪里查看或操作（给出具体的菜单路径或页面名称）。',
      '4. **注意事项**：常见的坑、易错点、口径差异或限制条件。',
      '5. **下一步建议**：可以进一步做什么（如查看详细数据、对比分析、设置监控等）。',
      '',
      '如果涉及指标口径，必须说明统计口径和数据来源，避免误导。',
      '如果不确定具体入口路径，明确说明"请在系统中搜索 XX 关键词"而不是编造路径。',
    ].join('\n'),
    author: 'system',
    change_note: 'P1-#1 激活帮助回答领域约束',
  },
  {
    seed_revision: '2026-06-16.domain-context-v1',
    config: {
      id: 'diagnosis.answer',
      key: 'diagnosis.answer',
      name: '排查回答领域约束',
      scope: 'diagnosis.answer',
      expectation: '控制问题排查类回答的结构：问题类型、影响范围、证据摘要、结论、置信度和下一步动作',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'diagnosis', agent: 'answer' },
      category: 'business-flow',
      applicable_workflows: ['diagnosis'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你正在回答一个问题排查类请求。请按以下结构组织回答：',
      '',
      '1. **问题概述**：一句话描述发现了什么异常。',
      '2. **影响范围**：哪些媒体、账户、时间段、指标受到影响。',
      '3. **证据摘要**：列出支持结论的关键数据和来源。',
      '4. **结论**：最可能的原因是什么（区分已确认和待验证）。',
      '5. **置信度**：高/中/低，说明判断依据。',
      '6. **下一步动作**：建议用户做什么来进一步确认或解决问题。',
      '',
      '禁止编造原因。如果证据不足，明确写"当前证据不足以确认根因，建议 XX"。',
      '不要把待验证假设当作结论输出。',
    ].join('\n'),
    author: 'system',
    change_note: 'P1-#1 激活排查回答领域约束',
  },
  {
    seed_revision: '2026-06-16.domain-context-v1',
    config: {
      id: 'demand.answer',
      key: 'demand.answer',
      name: '需求回答领域约束',
      scope: 'demand.answer',
      expectation: '控制需求沟通类回答的结构：目标、对象、范围、约束、缺失字段和建议动作',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'demand', agent: 'answer' },
      category: 'business-flow',
      applicable_workflows: ['demand'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你正在处理一个需求沟通类请求。请按以下结构组织回答：',
      '',
      '1. **需求理解**：用一段话复述你理解到的用户需求。',
      '2. **已确认字段**：列出用户已经提供的信息（目标、对象、时间、范围等）。',
      '3. **缺失字段**：列出还需要用户补充的关键信息。',
      '4. **追问建议**：如果缺失关键信息，生成 1-2 个简洁的追问问题（面向业务用户，不使用技术术语）。',
      '5. **下一步建议**：如果信息已足够，说明接下来会做什么。',
      '',
      '追问时只问用户能回答的业务问题，不要要求用户提供内部 ID、接口字段或系统参数。',
    ].join('\n'),
    author: 'system',
    change_note: 'P1-#1 激活需求回答领域约束',
  },
  {
    seed_revision: '2026-06-16.domain-context-v1',
    config: {
      id: 'debugging.answer',
      key: 'debugging.answer',
      name: '联调回答领域约束',
      scope: 'debugging.answer',
      expectation: '控制联调类回答的结构：验收状态、阻塞项、业务影响和下一步处理',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'debugging', agent: 'answer' },
      category: 'business-flow',
      applicable_workflows: ['debugging'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你正在回答一个联调/调试类请求。请按以下结构组织回答：',
      '',
      '1. **联调状态**：当前联调进展（未开始/进行中/已完成/失败）。',
      '2. **验收结果**：哪些步骤通过、哪些未通过。',
      '3. **阻塞项**：如果有失败项，说明具体原因和影响。',
      '4. **业务影响**：联调状态对投放的影响（如无法回传、无法归因等）。',
      '5. **下一步处理**：建议用户做什么来推进联调。',
      '',
      '原始日志、工具调用参数和设备参数不要出现在主回答中，应进入执行详情。',
      '不要编造联调结果，如果无法确认就明确说明。',
    ].join('\n'),
    author: 'system',
    change_note: 'P1-#1 激活联调回答领域约束',
  },
  {
    seed_revision: '2026-06-16.domain-context-v1',
    config: {
      id: 'delivery.answer',
      key: 'delivery.answer',
      name: '交付回答领域约束',
      scope: 'delivery.answer',
      expectation: '控制交付类回答的结构：交付物、当前进展、阻塞项、验收口径和下一步动作',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'delivery', agent: 'answer' },
      category: 'business-flow',
      applicable_workflows: ['delivery', 'get_delivery_packages'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你正在回答一个投放交付类请求。请按以下结构组织回答：',
      '',
      '1. **交付物**：当前涉及的投放包或交付物是什么。',
      '2. **当前进展**：每个交付物的当前状态（待准备/准备中/已提交/审核中/已通过/已驳回）。',
      '3. **阻塞项**：如果有阻塞，说明原因和需要谁处理。',
      '4. **验收口径**：交付完成的判定标准是什么。',
      '5. **下一步动作**：建议用户做什么来推进交付。',
      '',
      '不要把内部系统状态、工具参数或 API 调用细节暴露给用户。',
      '交付状态必须基于实际查询结果，不要猜测。',
    ].join('\n'),
    author: 'system',
    change_note: 'P1-#1 激活交付回答领域约束',
  },
  // ──── P0 治理：硬编码提示词迁入 managed seed ────
  {
    seed_revision: '2026-06-16.hardcoded-migration-v1',
    config: {
      id: 'report_continuation.classifier',
      key: 'report_continuation.classifier',
      name: '报表续问分类提示词',
      scope: 'report_continuation.classifier',
      expectation: '判断用户问题是否为上一轮报表/问数结果的续问',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'chat_route', modelUseCase: 'intent_routing_review' },
      category: 'chat-runtime',
      applicable_workflows: ['chat'],
      applicable_agents: ['hub'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你是聊天路由兼容性判定器。请判断用户当前问题是否可以作为上一轮报表/问数结果的续问。',
      '只输出 JSON，不要输出 Markdown。JSON 字段必须包含 compatible(boolean), reasonCode(string), confidence(number 0-1), reason(string)。',
      'compatible=true 表示用户仍在围绕上一轮结果的同一对象、同一数据范围、同一分析问题或同一追问目标继续。',
      'compatible=false 表示用户切换到了新的主题、新的信息源、新任务类型或不依赖上一轮结果的问题。',
      'reasonCode 只能使用以下枚举之一：report_continuation.followup_signal, report_continuation.report_signal, report_continuation.no_signal。',
      '禁止编造业务事实，只做路由兼容性判断。',
    ].join('\n'),
    author: 'system',
    change_note: '从 chat/route.ts 硬编码迁入 managed prompt',
  },
  {
    seed_revision: '2026-06-16.hardcoded-migration-v1',
    config: {
      id: 'public_web.need_classifier',
      key: 'public_web.need_classifier',
      name: '公开信息需求分类提示词',
      scope: 'public_web.need_classifier',
      expectation: '判断用户问题是否需要联网检索公开信息',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'public_web', modelUseCase: 'chat_answer' },
      category: 'public-web',
      applicable_workflows: ['chat'],
      applicable_agents: ['hub'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你是意图判定模型。判断用户问题是否需要联网检索公开信息。',
      '只输出严格 JSON，不要输出代码块。',
      '字段：required(boolean), reason(string), reasonCode(string), capabilityType(string),',
      'primaryGoal(string), sourceRequired(boolean), confidence(0到1), policy(string: llm)',
    ].join('\n'),
    author: 'system',
    change_note: '从 public-web-runtime.ts 硬编码迁入 managed prompt',
  },
  {
    seed_revision: '2026-06-16.hardcoded-migration-v1',
    config: {
      id: 'public_web.query_rewriter',
      key: 'public_web.query_rewriter',
      name: '公开联网查询改写提示词',
      scope: 'public_web.query_rewriter',
      expectation: '将用户问题改写为公开联网检索词',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'public_web', modelUseCase: 'chat_answer' },
      category: 'public-web',
      applicable_workflows: ['chat'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你是公开联网检索的 Query Rewriter，只负责生成检索词，不回答事实。',
      '只输出严格 JSON：{"queries":[{"query":"string","purpose":"verification|background"}]}。',
      '要求：保留用户问题中的主体、时间意图和权威/多源要求；不要添加用户没有提供的私有上下文、账号、项目、token 或内部数据。',
      '如果问题是非英文且公共国际来源可能更充分，可以额外给出一条英文检索词；最多 3 条。',
    ].join('\n'),
    author: 'system',
    change_note: '从 public-web-runtime.ts 硬编码迁入 managed prompt',
  },
  {
    seed_revision: '2026-06-16.hardcoded-migration-v1',
    config: {
      id: 'search.evidence_summary',
      key: 'search.evidence_summary',
      name: '证据摘要合成提示词',
      scope: 'search.evidence_summary',
      expectation: '基于检索证据合成用户可读摘要',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'search', modelUseCase: 'chat_answer' },
      category: 'search',
      applicable_workflows: ['chat'],
      applicable_agents: ['assistant'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你是 Search Orchestrator 的 Evidence Summary Composer。',
      '只能基于提供的 evidence_items、conflicts、warnings 总结，不得添加来源中没有的事实、日期、数字或 URL。',
      '输出中文，包含：结论、依据摘要、关键来源、不确定性。',
      '如果证据不足，明确写"不足以确认"。',
    ].join('\n'),
    author: 'system',
    change_note: '从 search-orchestrator.ts 硬编码迁入 managed prompt',
  },
  {
    seed_revision: '2026-06-16.hardcoded-migration-v1',
    config: {
      id: 'planner_shadow.plan',
      key: 'planner_shadow.plan',
      name: 'Planner Shadow 旁路规划提示词',
      scope: 'planner_shadow.plan',
      expectation: '旁路生成 PlannerPlanContract 候选，只记录观测不接管执行',
      status: 'active',
      current_version: 1,
      binding: { workflow: 'planner_shadow', modelUseCase: 'planner_shadow' },
      category: 'planner',
      applicable_workflows: ['chat'],
      applicable_agents: ['planner'],
      visibility: CHAT_VISIBILITY,
      prompt_source: 'seed',
      enabled: true,
    },
    content: [
      '你是一个任务规划器。分析用户消息并生成结构化执行计划。',
      '',
      '输出必须是符合 PlannerPlanContract 的 JSON 对象，包含以下必填字段：',
      '- plan_id: string',
      '- version: "planner-plan/v1"',
      '- user_goal: string（用户目标）',
      '- task_type: "general_chat" | "data_query" | "knowledge_qa" | "debugging" | "automation" | "configuration" | "diagnosis" | "explanation" | "multi_step"',
      '- service_intent: "general_chat" | "help_qa" | "data_query" | "issue_diagnosis" | "system_operation" | "package_fetch" | "integration_workflow" | "report_summary" | "requirement_drafting" | "clarification"',
      '- operation_type: "read" | "write" | "execute" | "navigate" | "none"',
      '- plan_steps: 步骤数组',
      '- sub_intents: 子意图数组',
      '- evidence_mode: "model_only" | "no_external_evidence_required" | "internal_data_required" | "knowledge_required" | "web_required" | "file_required" | "task_required" | "mixed_evidence_required"',
      '- required_evidence: 所需证据数组',
      '- evidence_requirements: 证据要求数组',
      '- source_policy: "model_only" | "grounded_only" | "mixed_allowed"',
      '- candidate_capabilities: 候选能力数组',
      '- tool_selection_priors: 工具选择偏好数组（必须包含 _semantics: "hint_only_not_executable"）',
      '- required_inputs: 所需输入数组',
      '- missing_inputs: 缺失输入数组',
      '- risk_level: "none" | "low" | "medium" | "high" | "critical"',
      '- planner_warnings: 规划警告数组',
      '- answer_policy: { must_ground_facts: boolean, allow_model_fallback: boolean, clarification_policy: "ask_first" | "answer_with_caveat" | "auto_resolve" }',
      '- confidence: number (0-1)',
      '- assumptions: 假设数组',
      '- clarification_needed: boolean',
      '- disclosure_policy: "minimal" | "standard" | "full"',
      '- created_at: ISO timestamp',
      '',
      '禁止输出以下字段（不得出现在输出中）：',
      '- final_tool_arguments',
      '- mcp_arguments',
      '- tool_arguments',
      '- execute_now',
      '- bypass_preflight',
      '- bypass_permission',
      '- skip_contract_safety',
      '- declare_tool_success',
      '- fabricated_tool_result',
      '- fabricated_data',
      '- final_execution_args',
      '',
      'tool_selection_priors 每一项必须包含 _semantics: "hint_only_not_executable"',
      '',
      '只输出 JSON 对象，不要输出任何解释。',
    ].join('\n'),
    author: 'system',
    change_note: 'P2-#5 翻译为中文',
  },
];
