MOCK_SCOPE = {
    "media": "巨量",
    "game": "指间山海",
    "device_path": "安卓真机 / 已安装游戏",
    "acceptance": ["入口生成", "抖音消费入口", "打开游戏", "启动", "登录"],
}

MOCK_SUMMARY_CARDS = [
    {
        "title": "首轮范围",
        "value": "巨量 × 指间山海",
        "detail": "只跑一条标准媒体链路，不做多媒体并行和 iOS 分支。",
        "tone": "brand",
    },
    {
        "title": "设备路径",
        "value": "安卓 / 已安装",
        "detail": "先绕开下载与安装中间态，把广告侧推进到游戏启动链路。",
        "tone": "neutral",
    },
    {
        "title": "验收口径",
        "value": "启动 + 登录",
        "detail": "归因、回推、付费先降级为后续增强项，不作为首轮硬门槛。",
        "tone": "success",
    },
    {
        "title": "当前重点",
        "value": "先走通主链路",
        "detail": "先验证入口送达、抖音消费入口、广告到游戏、游戏登录四个硬节点。",
        "tone": "warning",
    },
]

MOCK_CHECKLIST = [
    {
        "id": "media",
        "title": "巨量联调账户与入口页面固定",
        "status": "ready",
        "owner": "广告支持",
        "detail": "首轮只保留一套巨量联调页面和一条标准入口生成路径。",
    },
    {
        "id": "device",
        "title": "安卓测试机已装抖音和指间山海",
        "status": "ready",
        "owner": "测试 / 广告支持",
        "detail": "设备需要能被稳定唤醒和控制，不切换多机型。",
    },
    {
        "id": "douyin",
        "title": "抖音账号登录态可用",
        "status": "ready",
        "owner": "投放",
        "detail": "首轮目标是不被登录、人脸识别、风控和弹窗直接阻断。",
    },
    {
        "id": "game-account",
        "title": "指间山海测试账号可稳定登录",
        "status": "ready",
        "owner": "测试 / 运营",
        "detail": "首轮只验证登录，不验证付费，不走验证码和复杂风控路径。",
    },
    {
        "id": "precheck",
        "title": "联调前置与设备白名单已确认",
        "status": "ready",
        "owner": "广告支持",
        "detail": "即使首轮不验归因，也把 QA、数据验收、设备登记和白名单作为固定前置。",
    },
]

MOCK_STEPS = [
    {
        "id": "step-1",
        "index": 1,
        "title": "创建联调任务",
        "stage": "任务初始化",
        "goal": "把本次巨量 × 指间山海联调变成唯一任务对象。",
        "status": "pending",
        "inputs": ["媒体=巨量", "项目=指间山海", "联调类型=安卓已安装路径", "验收=启动+登录"],
        "outputs": ["task_id", "任务摘要", "待执行状态"],
        "success_criteria": ["任务成功创建", "当前范围与验收口径已锁定"],
        "failure_modes": ["关键信息不完整", "前置校验未通过"],
        "next_action": "进入巨量后台并生成本次联调入口。",
    },
    {
        "id": "step-2",
        "index": 2,
        "title": "浏览器登录巨量后台",
        "stage": "浏览器自动化",
        "goal": "进入巨量可操作页面，准备创建本次联调入口。",
        "status": "pending",
        "inputs": ["巨量账号", "后台目标页面"],
        "outputs": ["登录态", "后台页面上下文"],
        "success_criteria": ["已进入可操作页面", "后续入口创建控件可见"],
        "failure_modes": ["登录失败", "验证码或风控", "页面结构变化"],
        "next_action": "创建当前任务唯一对应的二维码或直链入口。",
    },
    {
        "id": "step-3",
        "index": 3,
        "title": "生成联调入口",
        "stage": "浏览器自动化",
        "goal": "产出本次任务可消费的二维码或直链。",
        "status": "pending",
        "inputs": ["后台页面上下文", "联调目标", "标准配置模板"],
        "outputs": ["入口对象", "入口绑定结果"],
        "success_criteria": ["入口生成成功", "入口与 task_id 绑定清楚"],
        "failure_modes": ["配置失败", "入口生成失败", "权限不足"],
        "next_action": "把入口以最稳定的方式送达安卓设备。",
    },
    {
        "id": "step-4",
        "index": 4,
        "title": "入口送达安卓设备",
        "stage": "设备桥接",
        "goal": "让安卓测试机稳定拿到本次任务入口，不再人工重找。",
        "status": "pending",
        "inputs": ["入口对象", "安卓设备", "设备侧读取方式"],
        "outputs": ["设备可访问入口", "入口送达状态"],
        "success_criteria": ["入口已送达且未串任务", "后续脚本可直接消费"],
        "failure_modes": ["图片/链接到不了手机", "入口与任务错配", "设备侧读不到入口"],
        "next_action": "调起抖音并消费本次联调入口。",
    },
    {
        "id": "step-5",
        "index": 5,
        "title": "打开抖音并进入消费入口页",
        "stage": "安卓真机控制",
        "goal": "让测试机在抖音内进入扫一扫或等价入口页。",
        "status": "pending",
        "inputs": ["设备连接状态", "抖音登录态", "入口消费方式"],
        "outputs": ["抖音前台页", "可消费入口页"],
        "success_criteria": ["抖音已打开", "扫一扫或等价入口可操作"],
        "failure_modes": ["设备不可控", "抖音弹窗或风控", "入口页找不到"],
        "next_action": "识别入口并进入广告页或落地页。",
    },
    {
        "id": "step-6",
        "index": 6,
        "title": "消费联调入口并进入广告页",
        "stage": "安卓真机控制",
        "goal": "让抖音真正消费入口并跳转到正确广告页/落地页。",
        "status": "pending",
        "inputs": ["二维码图片或直链", "抖音当前页面"],
        "outputs": ["广告页状态", "落地页状态"],
        "success_criteria": ["已进入本次任务对应广告页", "页面稳定可继续"],
        "failure_modes": ["扫码失败", "链接不可消费", "跳转错误或风控阻断"],
        "next_action": "从广告链路推进到已安装的指间山海。",
    },
    {
        "id": "step-7",
        "index": 7,
        "title": "从广告页打开指间山海",
        "stage": "广告到游戏",
        "goal": "沿已安装路径把链路稳定推进到游戏前台。",
        "status": "pending",
        "inputs": ["广告/落地页", "已安装游戏状态"],
        "outputs": ["游戏启动链路", "当前前台应用"],
        "success_criteria": ["已识别 CTA", "点击后目标游戏进入前台"],
        "failure_modes": ["CTA 找不到", "跳转失败", "游戏未被拉起"],
        "next_action": "稳定处理首屏并完成登录动作。",
    },
    {
        "id": "step-8",
        "index": 8,
        "title": "触发启动与登录",
        "stage": "游戏侧动作",
        "goal": "把 UI 自动化推进到真实业务事件已经发生的状态。",
        "status": "pending",
        "inputs": ["游戏前台状态", "测试账号", "首屏弹窗状态"],
        "outputs": ["启动结果", "登录结果", "事件时间锚点"],
        "success_criteria": ["游戏稳定启动", "测试账号登录完成"],
        "failure_modes": ["首屏卡死", "登录失败", "页面结构差异过大"],
        "next_action": "首轮先以启动+登录主链路通过作为结论。",
    },
    {
        "id": "step-9",
        "index": 9,
        "title": "归因检查",
        "stage": "后续增强",
        "goal": "为第二轮补齐报表与明细检查，不纳入首轮硬门槛。",
        "status": "info",
        "inputs": ["事件时间锚点", "报表页", "明细页"],
        "outputs": ["归因检查结论"],
        "success_criteria": ["能判定归因正常、异常或待确认"],
        "failure_modes": ["事件未归因", "结果不透明", "数据延迟"],
        "next_action": "首轮只保留位置，不阻断主链路通过。",
    },
    {
        "id": "step-10",
        "index": 10,
        "title": "回推检查与结果收口",
        "stage": "后续增强",
        "goal": "为第二轮补齐媒体回推校验和完整联调报告。",
        "status": "info",
        "inputs": ["回推配置", "媒体侧结果"],
        "outputs": ["联调最终结论", "下一步建议"],
        "success_criteria": ["能判定回推正常、异常或待人工处理"],
        "failure_modes": ["媒体未收到回推", "配置缺失", "链路异常"],
        "next_action": "首轮先输出主链路跑通到登录的工作台结论。",
    },
]

MOCK_REPLAY_EVENTS = [
    {"offset_ms": 0, "step_id": "step-1", "step_status": "running", "level": "info", "message": "联调任务创建中，范围锁定为巨量 × 指间山海 × 安卓已安装路径。"},
    {"offset_ms": 900, "step_id": "step-1", "step_status": "success", "level": "success", "message": "任务创建成功，首轮验收口径已锁定为启动 + 登录。"},
    {"offset_ms": 1400, "step_id": "step-2", "step_status": "running", "level": "info", "message": "浏览器自动化已打开巨量后台，准备进入联调入口页面。"},
    {"offset_ms": 2600, "step_id": "step-2", "step_status": "success", "level": "success", "message": "巨量后台登录成功，目标页面上下文已就绪。"},
    {"offset_ms": 3200, "step_id": "step-3", "step_status": "running", "level": "info", "message": "创建本次任务唯一联调入口。"},
    {"offset_ms": 4600, "step_id": "step-3", "step_status": "success", "level": "success", "message": "入口生成完成，当前任务已绑定二维码/直链对象。"},
    {"offset_ms": 5200, "step_id": "step-4", "step_status": "running", "level": "warning", "message": "尝试通过固定桥接路径把入口送到安卓测试机。"},
    {"offset_ms": 6600, "step_id": "step-4", "step_status": "success", "level": "success", "message": "安卓设备已拿到入口，后续脚本无需人工重新查找。"},
    {"offset_ms": 7200, "step_id": "step-5", "step_status": "running", "level": "info", "message": "唤醒设备并打开抖音，处理首屏弹窗与登录态。"},
    {"offset_ms": 8600, "step_id": "step-5", "step_status": "success", "level": "success", "message": "抖音入口页可操作，准备消费本次联调入口。"},
    {"offset_ms": 9200, "step_id": "step-6", "step_status": "running", "level": "info", "message": "抖音开始消费联调入口并尝试跳转到广告页。"},
    {"offset_ms": 10800, "step_id": "step-6", "step_status": "success", "level": "success", "message": "已进入本次任务对应广告页，页面稳定可继续。"},
    {"offset_ms": 11400, "step_id": "step-7", "step_status": "running", "level": "info", "message": "沿已安装路径点击打开，推进到指间山海前台。"},
    {"offset_ms": 13000, "step_id": "step-7", "step_status": "success", "level": "success", "message": "指间山海已成功拉起，当前前台应用切换完成。"},
    {"offset_ms": 13600, "step_id": "step-8", "step_status": "running", "level": "warning", "message": "清理首屏中间态并使用测试账号执行登录。"},
    {"offset_ms": 15400, "step_id": "step-8", "step_status": "success", "level": "success", "message": "启动与登录完成，首轮主链路可判定为已跑通。"},
]

MOCK_RISKS = [
    {
        "title": "入口送达安卓设备",
        "detail": "电脑侧产物如何稳定进入手机仍然是第一硬风险，后续要固定唯一桥接路径。",
        "severity": "high",
    },
    {
        "title": "抖音入口消费方式",
        "detail": "需要尽快验证是必须走扫一扫，还是可以被稳定替换为直链消费。",
        "severity": "high",
    },
    {
        "title": "广告页到游戏的已安装路径",
        "detail": "首轮先走已安装游戏路径，暂时不把完整下载与安装链路纳入成功标准。",
        "severity": "medium",
    },
    {
        "title": "游戏首屏差异与登录稳定性",
        "detail": "指间山海首屏弹窗、账号风控和登录路径必须在首轮固定，不做通用脚本。",
        "severity": "medium",
    },
]
