MOCK_FLOW_NODES = [
    {"id": "login_event", "label": "登录事件", "type": "entry", "user_count": 118},
    {"id": "source_app", "label": "APP", "type": "source", "user_count": 72},
    {"id": "source_h5", "label": "H5", "type": "source", "user_count": 38},
    {"id": "invalid_drop", "label": "字段缺失丢弃", "type": "exception", "user_count": 8},
    {"id": "user_identify", "label": "用户识别", "type": "decision", "user_count": 110},
    {"id": "new_user", "label": "新用户", "type": "decision", "user_count": 42},
    {"id": "existing_user", "label": "老用户", "type": "decision", "user_count": 50},
    {"id": "exception_queue", "label": "异常归因队列", "type": "exception", "user_count": 18},
    {"id": "device_match", "label": "设备归因匹配", "type": "process", "user_count": 104},
    {"id": "window_normal", "label": "正常窗口<1min", "type": "window", "user_count": 46},
    {"id": "window_exception", "label": "异常窗口<1h", "type": "window", "user_count": 22},
    {"id": "ad_attributed", "label": "广告归因成功", "type": "result", "user_count": 58},
    {"id": "retry_queue", "label": "重试队列", "type": "result", "user_count": 26},
    {"id": "organic_traffic", "label": "自然流量", "type": "result", "user_count": 20},
    {"id": "attr_res_activation", "label": "归因结果表", "type": "storage", "user_count": 58},
    {"id": "user_table_update", "label": "用户表更新", "type": "storage", "user_count": 78},
]

MOCK_FLOW_LINKS = [
    {"source": "login_event", "target": "source_app", "value": 72},
    {"source": "login_event", "target": "source_h5", "value": 38},
    {"source": "login_event", "target": "invalid_drop", "value": 8},
    {"source": "source_app", "target": "user_identify", "value": 72},
    {"source": "source_h5", "target": "user_identify", "value": 38},
    {"source": "user_identify", "target": "new_user", "value": 42},
    {"source": "user_identify", "target": "existing_user", "value": 50},
    {"source": "user_identify", "target": "exception_queue", "value": 18},
    {"source": "new_user", "target": "device_match", "value": 42},
    {"source": "existing_user", "target": "device_match", "value": 50},
    {"source": "exception_queue", "target": "device_match", "value": 12},
    {"source": "device_match", "target": "window_normal", "value": 46},
    {"source": "device_match", "target": "window_exception", "value": 22},
    {"source": "device_match", "target": "retry_queue", "value": 16},
    {"source": "device_match", "target": "organic_traffic", "value": 20},
    {"source": "window_normal", "target": "ad_attributed", "value": 46},
    {"source": "window_exception", "target": "ad_attributed", "value": 12},
    {"source": "window_exception", "target": "retry_queue", "value": 10},
    {"source": "ad_attributed", "target": "attr_res_activation", "value": 58},
    {"source": "ad_attributed", "target": "user_table_update", "value": 58},
    {"source": "organic_traffic", "target": "user_table_update", "value": 20},
]

MOCK_USERS = [
    {
        "user_id": "u1001",
        "device_id": "d-app-01",
        "source_type": "app",
        "user_type": "new_user",
        "current_node": "user_table_update",
        "result_node": "ad_attributed",
        "visited_nodes": [
            "login_event",
            "source_app",
            "user_identify",
            "new_user",
            "device_match",
            "window_normal",
            "ad_attributed",
            "attr_res_activation",
            "user_table_update",
        ],
    },
    {
        "user_id": "u1002",
        "device_id": "d-h5-02",
        "source_type": "h5",
        "user_type": "existing_user",
        "current_node": "retry_queue",
        "result_node": "retry_queue",
        "visited_nodes": [
            "login_event",
            "source_h5",
            "user_identify",
            "existing_user",
            "device_match",
            "window_exception",
            "retry_queue",
        ],
    },
    {
        "user_id": "u1003",
        "device_id": "d-app-03",
        "source_type": "app",
        "user_type": "new_user",
        "current_node": "user_table_update",
        "result_node": "organic_traffic",
        "visited_nodes": [
            "login_event",
            "source_app",
            "user_identify",
            "new_user",
            "device_match",
            "organic_traffic",
            "user_table_update",
        ],
    },
    {
        "user_id": "u1004",
        "device_id": "d-app-04",
        "source_type": "app",
        "user_type": "existing_user",
        "current_node": "attr_res_activation",
        "result_node": "ad_attributed",
        "visited_nodes": [
            "login_event",
            "source_app",
            "user_identify",
            "existing_user",
            "device_match",
            "window_normal",
            "ad_attributed",
            "attr_res_activation",
            "user_table_update",
        ],
    },
    {
        "user_id": "u1005",
        "device_id": "d-h5-05",
        "source_type": "h5",
        "user_type": "new_user",
        "current_node": "exception_queue",
        "result_node": "retry_queue",
        "visited_nodes": [
            "login_event",
            "source_h5",
            "user_identify",
            "exception_queue",
            "device_match",
            "window_exception",
            "retry_queue",
        ],
    },
    {
        "user_id": "u1006",
        "device_id": "d-app-06",
        "source_type": "app",
        "user_type": "existing_user",
        "current_node": "invalid_drop",
        "result_node": "invalid_drop",
        "visited_nodes": [
            "login_event",
            "invalid_drop",
        ],
    },
    {
        "user_id": "u1007",
        "device_id": "d-h5-07",
        "source_type": "h5",
        "user_type": "existing_user",
        "current_node": "user_table_update",
        "result_node": "ad_attributed",
        "visited_nodes": [
            "login_event",
            "source_h5",
            "user_identify",
            "existing_user",
            "device_match",
            "window_exception",
            "ad_attributed",
            "attr_res_activation",
            "user_table_update",
        ],
    },
    {
        "user_id": "u1008",
        "device_id": "d-app-08",
        "source_type": "app",
        "user_type": "new_user",
        "current_node": "device_match",
        "result_node": "retry_queue",
        "visited_nodes": [
            "login_event",
            "source_app",
            "user_identify",
            "new_user",
            "exception_queue",
            "device_match",
            "retry_queue",
        ],
    },
    {
        "user_id": "u1009",
        "device_id": "d-h5-09",
        "source_type": "h5",
        "user_type": "new_user",
        "current_node": "organic_traffic",
        "result_node": "organic_traffic",
        "visited_nodes": [
            "login_event",
            "source_h5",
            "user_identify",
            "new_user",
            "device_match",
            "organic_traffic",
            "user_table_update",
        ],
    },
    {
        "user_id": "u1010",
        "device_id": "d-app-10",
        "source_type": "app",
        "user_type": "existing_user",
        "current_node": "attr_res_activation",
        "result_node": "ad_attributed",
        "visited_nodes": [
            "login_event",
            "source_app",
            "user_identify",
            "existing_user",
            "device_match",
            "window_normal",
            "ad_attributed",
            "attr_res_activation",
            "user_table_update",
        ],
    },
    {
        "user_id": "u1011",
        "device_id": "d-app-11",
        "source_type": "app",
        "user_type": "new_user",
        "current_node": "user_table_update",
        "result_node": "ad_attributed",
        "visited_nodes": [
            "login_event",
            "source_app",
            "user_identify",
            "new_user",
            "device_match",
            "window_exception",
            "ad_attributed",
            "attr_res_activation",
            "user_table_update",
        ],
    },
    {
        "user_id": "u1012",
        "device_id": "d-h5-12",
        "source_type": "h5",
        "user_type": "existing_user",
        "current_node": "organic_traffic",
        "result_node": "organic_traffic",
        "visited_nodes": [
            "login_event",
            "source_h5",
            "user_identify",
            "existing_user",
            "device_match",
            "organic_traffic",
            "user_table_update",
        ],
    },
    {
        "user_id": "u1013",
        "device_id": "d-app-13",
        "source_type": "app",
        "user_type": "new_user",
        "current_node": "retry_queue",
        "result_node": "retry_queue",
        "visited_nodes": [
            "login_event",
            "source_app",
            "user_identify",
            "new_user",
            "device_match",
            "window_exception",
            "retry_queue",
        ],
    },
    {
        "user_id": "u1014",
        "device_id": "d-h5-14",
        "source_type": "h5",
        "user_type": "new_user",
        "current_node": "exception_queue",
        "result_node": "retry_queue",
        "visited_nodes": [
            "login_event",
            "source_h5",
            "user_identify",
            "new_user",
            "exception_queue",
            "device_match",
            "retry_queue",
        ],
    },
    {
        "user_id": "u1015",
        "device_id": "d-h5-15",
        "source_type": "h5",
        "user_type": "existing_user",
        "current_node": "invalid_drop",
        "result_node": "invalid_drop",
        "visited_nodes": [
            "login_event",
            "invalid_drop",
        ],
    },
    {
        "user_id": "u1016",
        "device_id": "d-app-16",
        "source_type": "app",
        "user_type": "existing_user",
        "current_node": "user_table_update",
        "result_node": "ad_attributed",
        "visited_nodes": [
            "login_event",
            "source_app",
            "user_identify",
            "existing_user",
            "device_match",
            "window_normal",
            "ad_attributed",
            "attr_res_activation",
            "user_table_update",
        ],
    },
]

MOCK_USER_TRACES = {
    "u1001": [
        {"step": "login_event", "time": "10:00"},
        {"step": "source_app", "time": "10:00:10"},
        {"step": "user_identify", "time": "10:00:20"},
        {"step": "new_user", "time": "10:00:30"},
        {"step": "device_match", "time": "10:00:40"},
        {"step": "window_normal", "time": "10:00:50"},
        {"step": "ad_attributed", "time": "10:00:55"},
        {"step": "attr_res_activation", "time": "10:01:00"},
        {"step": "user_table_update", "time": "10:01:05"},
    ],
    "u1002": [
        {"step": "login_event", "time": "10:02:00"},
        {"step": "source_h5", "time": "10:02:08"},
        {"step": "user_identify", "time": "10:02:15"},
        {"step": "existing_user", "time": "10:02:25"},
        {"step": "device_match", "time": "10:02:40"},
        {"step": "window_exception", "time": "10:03:10"},
        {"step": "retry_queue", "time": "10:03:25"},
    ],
    "u1003": [
        {"step": "login_event", "time": "10:04:00"},
        {"step": "source_app", "time": "10:04:05"},
        {"step": "user_identify", "time": "10:04:12"},
        {"step": "new_user", "time": "10:04:20"},
        {"step": "device_match", "time": "10:04:40"},
        {"step": "organic_traffic", "time": "10:05:00"},
        {"step": "user_table_update", "time": "10:05:10"},
    ],
    "u1004": [
        {"step": "login_event", "time": "10:06:00"},
        {"step": "source_app", "time": "10:06:05"},
        {"step": "user_identify", "time": "10:06:12"},
        {"step": "existing_user", "time": "10:06:18"},
        {"step": "device_match", "time": "10:06:35"},
        {"step": "window_normal", "time": "10:06:50"},
        {"step": "ad_attributed", "time": "10:06:55"},
        {"step": "attr_res_activation", "time": "10:07:00"},
        {"step": "user_table_update", "time": "10:07:05"},
    ],
    "u1005": [
        {"step": "login_event", "time": "10:08:00"},
        {"step": "source_h5", "time": "10:08:08"},
        {"step": "user_identify", "time": "10:08:15"},
        {"step": "exception_queue", "time": "10:08:30"},
        {"step": "device_match", "time": "10:08:50"},
        {"step": "window_exception", "time": "10:09:10"},
        {"step": "retry_queue", "time": "10:09:25"},
    ],
    "u1006": [
        {"step": "login_event", "time": "10:10:00"},
        {"step": "invalid_drop", "time": "10:10:05"},
    ],
    "u1007": [
        {"step": "login_event", "time": "10:12:00"},
        {"step": "source_h5", "time": "10:12:05"},
        {"step": "user_identify", "time": "10:12:15"},
        {"step": "existing_user", "time": "10:12:25"},
        {"step": "device_match", "time": "10:12:40"},
        {"step": "window_exception", "time": "10:12:55"},
        {"step": "ad_attributed", "time": "10:13:10"},
        {"step": "attr_res_activation", "time": "10:13:18"},
        {"step": "user_table_update", "time": "10:13:26"},
    ],
    "u1008": [
        {"step": "login_event", "time": "10:14:00"},
        {"step": "source_app", "time": "10:14:05"},
        {"step": "user_identify", "time": "10:14:15"},
        {"step": "new_user", "time": "10:14:25"},
        {"step": "exception_queue", "time": "10:14:40"},
        {"step": "device_match", "time": "10:14:55"},
        {"step": "retry_queue", "time": "10:15:10"},
    ],
    "u1009": [
        {"step": "login_event", "time": "10:16:00"},
        {"step": "source_h5", "time": "10:16:05"},
        {"step": "user_identify", "time": "10:16:15"},
        {"step": "new_user", "time": "10:16:25"},
        {"step": "device_match", "time": "10:16:40"},
        {"step": "organic_traffic", "time": "10:16:55"},
        {"step": "user_table_update", "time": "10:17:05"},
    ],
    "u1010": [
        {"step": "login_event", "time": "10:18:00"},
        {"step": "source_app", "time": "10:18:05"},
        {"step": "user_identify", "time": "10:18:15"},
        {"step": "existing_user", "time": "10:18:25"},
        {"step": "device_match", "time": "10:18:40"},
        {"step": "window_normal", "time": "10:18:50"},
        {"step": "ad_attributed", "time": "10:19:00"},
        {"step": "attr_res_activation", "time": "10:19:10"},
        {"step": "user_table_update", "time": "10:19:20"},
    ],
    "u1011": [
        {"step": "login_event", "time": "10:20:00"},
        {"step": "source_app", "time": "10:20:06"},
        {"step": "user_identify", "time": "10:20:14"},
        {"step": "new_user", "time": "10:20:24"},
        {"step": "device_match", "time": "10:20:38"},
        {"step": "window_exception", "time": "10:20:52"},
        {"step": "ad_attributed", "time": "10:21:02"},
        {"step": "attr_res_activation", "time": "10:21:12"},
        {"step": "user_table_update", "time": "10:21:20"},
    ],
    "u1012": [
        {"step": "login_event", "time": "10:22:00"},
        {"step": "source_h5", "time": "10:22:05"},
        {"step": "user_identify", "time": "10:22:15"},
        {"step": "existing_user", "time": "10:22:25"},
        {"step": "device_match", "time": "10:22:38"},
        {"step": "organic_traffic", "time": "10:22:50"},
        {"step": "user_table_update", "time": "10:23:00"},
    ],
    "u1013": [
        {"step": "login_event", "time": "10:24:00"},
        {"step": "source_app", "time": "10:24:05"},
        {"step": "user_identify", "time": "10:24:15"},
        {"step": "new_user", "time": "10:24:24"},
        {"step": "device_match", "time": "10:24:37"},
        {"step": "window_exception", "time": "10:24:50"},
        {"step": "retry_queue", "time": "10:25:02"},
    ],
    "u1014": [
        {"step": "login_event", "time": "10:26:00"},
        {"step": "source_h5", "time": "10:26:06"},
        {"step": "user_identify", "time": "10:26:16"},
        {"step": "new_user", "time": "10:26:26"},
        {"step": "exception_queue", "time": "10:26:38"},
        {"step": "device_match", "time": "10:26:52"},
        {"step": "retry_queue", "time": "10:27:04"},
    ],
    "u1015": [
        {"step": "login_event", "time": "10:28:00"},
        {"step": "invalid_drop", "time": "10:28:04"},
    ],
    "u1016": [
        {"step": "login_event", "time": "10:30:00"},
        {"step": "source_app", "time": "10:30:05"},
        {"step": "user_identify", "time": "10:30:15"},
        {"step": "existing_user", "time": "10:30:25"},
        {"step": "device_match", "time": "10:30:38"},
        {"step": "window_normal", "time": "10:30:48"},
        {"step": "ad_attributed", "time": "10:31:00"},
        {"step": "attr_res_activation", "time": "10:31:10"},
        {"step": "user_table_update", "time": "10:31:20"},
    ],
}
