#FROM python:3.11-slim
FROM sjb-storage-registry.cn-hangzhou.cr.aliyuncs.com/ops_new/node-python:24.13.0

WORKDIR /app

COPY pyproject.toml .
COPY src/ ./src/

RUN python3 -m venv /app/venv && \
    /app/venv/bin/pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -e .

ENV PATH="/app/venv/bin:$PATH"

EXPOSE 8080

CMD ["uvicorn", "ad.app:app", "--host", "0.0.0.0", "--port", "8080"]
